In [40]:
# Demonstrate use of TensorFlow and PyTorch by implementing simple code in Python

In [41]:
# 1. TensorFlow

In [42]:
import tensorflow as tf

In [43]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(32, )),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [44]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [45]:
import numpy as np
x_train = np.random.rand(1000, 32)
y_train = np.random.randint(0, 10, size=(1000,))

In [46]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1083 - loss: 2.3565
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1077 - loss: 2.3160
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1299 - loss: 2.2965
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1175 - loss: 2.2791
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1306 - loss: 2.2904
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1296 - loss: 2.2795
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1473 - loss: 2.2732
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1551 - loss: 2.2654
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1545 - loss: 2.2579
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1510 - loss: 2.2542


In [47]:
# Other Operations in Tensorflow

In [48]:
import tensorflow as tf
import numpy as np

In [49]:
tensor_from_list = tf.constant([[1, 2], [3, 4]])
print(tensor_from_list)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [50]:
random_tensor = tf.random.uniform(shape=(2, 4), minval = 32, maxval = 64)
print(random_tensor)

tf.Tensor(
[[57.042496 37.50918  52.217247 56.58146 ]
 [34.233955 48.539467 50.77549  36.913376]], shape=(2, 4), dtype=float32)


In [51]:
zero_tensor = tf.zeros(shape=(2, 3))
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [52]:
one_tensor = tf.ones(shape=(2, 3))
print(one_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [53]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print(tf.add(a, b))
print(tf.subtract(a, b))
print(tf.multiply(a, b))
print(tf.divide(a, b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [54]:
np_arr = np.array([[1, 2], [3, 4]])
tensor_from_np = tf.convert_to_tensor(np_arr)
print(tensor_from_np)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [55]:
# 2. Keras

In [56]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [57]:
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(32,)))
model.add(Dense(10, activation='softmax'))

In [58]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [59]:
x_train = np.random.rand(1000, 32)
y_train = np.random.randint(0, 10, size=(1000, ))

In [60]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0941 - loss: 2.3740
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0916 - loss: 2.3130
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1147 - loss: 2.2959
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0930 - loss: 2.3070
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1387 - loss: 2.2881
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1287 - loss: 2.2869
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1727 - loss: 2.2685
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1657 - loss: 2.2560
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1617 - loss: 2.2479
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1755 - loss: 2.2466


In [61]:
# Other operations in keras

In [62]:
import tensorflow as tf
from tensorflow.keras import backend as k
import numpy as np

In [63]:
tensor_from_list = k.constant([[1, 2], [3, 4]])
print(tensor_from_list)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [64]:
a = k.constant([[1, 2], [3, 4]])
b = k.constant([[5, 6], [7, 8]])

print(k.eval(a+b))
print(k.eval(a-b))
print(k.eval(a*b))
print(k.eval(a/b))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333334]
 [0.42857143 0.5       ]]


In [65]:
concat_tensor = k.concatenate([a, b], axis = 0)
print(concat_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]], shape=(4, 2), dtype=float32)


In [66]:
tensor_reshape = k.reshape(concat_tensor, shape=(2, 4))
print(tensor_reshape)

tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32)


In [67]:
# 3. Theano

In [ ]:
import theano
import theano.tensor as T
import numpy as np

In [ ]:
x = T.dmatrix('x')
w = T.dmatrix('w')
b = T.dvector('b')

In [ ]:
y = T.dot(x, w) + b

In [ ]:
model = theano.function(inputs=[x, w, b], outputs=y)

In [ ]:
x_data = np.random.rand(100, 32)
w_data = np.random.rand(32, 10)
b_data = np.random.rand(10)

In [ ]:
output = model(x_data, w_data, b_data)
print(output)

In [ ]:
# other operations in theano

In [ ]:
a_val = np.array([[1, 2], [3, 4]], dtype=theano.config.floatX)
b_val = np.array([[5, 6], [7, 8]], dtype=theano.config.floatX)

In [ ]:
add_result = a + b
sub_result = a - b
mul_result = a * b
div_result = a / b

In [ ]:
f_add = theano.function([a, b], add_result)
f_sub = theano.function([a, b], sub_result)
f_mul = theano.function([a, b], mul_result)
f_div = theano.function([a, b], div_result)

print("Addition:\n", f_add(a_val, b_val))
print("Subtraction:\n", f_sub(a_val, b_val))
print("Multiplication:\n", f_mul(a_val, b_val))
print("Division:\n", f_div(a_val, b_val))

In [69]:
# 4. PyTorch

In [70]:
import torch
import torch.nn as nn
import torch.optim as optim

In [71]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(32, 64)
        self.fc2 = nn.Linear(64, 10)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

In [72]:
model = SimpleNN()

In [73]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [74]:
x_train = torch.rand(1000, 32)
y_train = torch.randint(0, 10, (1000,))

In [75]:
for epoch in range(10):
    model.train()
    optimizer.zero_grad()
    outputs = model(x_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    print(f'Epoch [{epoch+1}/10], Loss: {loss.item():.4f}')

Epoch [1/10], Loss: 2.3109
Epoch [2/10], Loss: 2.3075
Epoch [3/10], Loss: 2.3046
Epoch [4/10], Loss: 2.3021
Epoch [5/10], Loss: 2.2999
Epoch [6/10], Loss: 2.2981
Epoch [7/10], Loss: 2.2965
Epoch [8/10], Loss: 2.2951
Epoch [9/10], Loss: 2.2940
Epoch [10/10], Loss: 2.2929


In [76]:
# other operations in pytorch

In [77]:
data = [[1, 2], [3, 4]]
tensor_from_list = torch.tensor(data)
print("Tensor from list:\n", tensor_from_list)

random_tensor = torch.rand((2, 3))
print("Random tensor:\n", random_tensor)

zero_tensor = torch.zeros((2, 3))
print("Zero tensor:\n", zero_tensor)

ones_tensor = torch.ones((2, 3))
print("Ones tensor:\n", ones_tensor)

Tensor from list:
 tensor([[1, 2],
        [3, 4]])
Random tensor:
 tensor([[0.1530, 0.0269, 0.9049],
        [0.4769, 0.1833, 0.8903]])
Zero tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [78]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Subtraction:
 tensor([[-4., -4.],
        [-4., -4.]])
Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Division:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [79]:
sqrt_tensor = torch.sqrt(a)
print("Square root tensor:\n", sqrt_tensor)

exp_tensor = torch.exp(a)
print("Exponential tensor:\n", exp_tensor)

log_tensor = torch.log(a)
print("Logarithm tensor:\n", log_tensor)

Square root tensor:
 tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])
Exponential tensor:
 tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
Logarithm tensor:
 tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])


In [80]:
tensor_np = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
np_array = tensor_np.numpy()  # Convert to NumPy array
print("Converted to NumPy array:\n", np_array)

np_array = np.array([[5.0, 6.0], [7.0, 8.0]])
tensor_from_np = torch.from_numpy(np_array)  # Convert NumPy array to tensor
print("Converted back to Tensor:\n", tensor_from_np)

Converted to NumPy array:
 [[1. 2.]
 [3. 4.]]
Converted back to Tensor:
 tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)
