In [79]:
# Study of Deep learning Packages: Tensorflow, Keras, Theano and PyTorch. Document the distinct features and functionality of the packages.  

In [80]:
# 1. TensorFlow

In [81]:
import tensorflow as tf

In [82]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(32, )),
    tf.keras.layers.Dense(10, activation='softmax')
])

C:\Program Files\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [83]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [84]:
import numpy as np
x_train = np.random.rand(1000, 32)
y_train = np.random.randint(0, 10, size=(1000,))

In [85]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1158 - loss: 2.3467
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1396 - loss: 2.2985
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1260 - loss: 2.2987
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1252 - loss: 2.2750
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1559 - loss: 2.2681
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1466 - loss: 2.2703
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1560 - loss: 2.2598
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1747 - loss: 2.2514
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1896 - loss: 2.2338
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2041 - loss: 2.2360


In [86]:
# Other Operations in Tensorflow

In [87]:
import tensorflow as tf
import numpy as np

In [88]:
tensor_from_list = tf.constant([[1, 2], [3, 4]])
print(tensor_from_list)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [89]:
zero_tensor = tf.zeros(shape=(2, 3))
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [90]:
one_tensor = tf.ones(shape=(2, 3))
print(one_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [91]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print(tf.add(a, b))
print(tf.subtract(a, b))
print(tf.multiply(a, b))
print(tf.divide(a, b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [92]:
np_arr = np.array([[1, 2], [3, 4]])
tensor_from_np = tf.convert_to_tensor(np_arr)
print(tensor_from_np)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [93]:
tensor_to_reshape = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
reshaped_tensor = tf.reshape(tensor_to_reshape, shape=(4, 2))
print("Reshaped tensor:\n", reshaped_tensor)
sliced_tensor = tensor_to_reshape[:, 1:3]
print("Sliced tensor:\n", sliced_tensor)

Reshaped tensor:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
Sliced tensor:
 tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [95]:
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6]])

concatenated_tensor = tf.concat([tensor_a, tensor_b], axis=0)
print("Concatenated tensor:\n", concatenated_tensor)

Concatenated tensor:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [97]:
import tensorflow as tf

tensor_from_list = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

sqrt_tensor = tf.sqrt(tensor_from_list)
print("Square root tensor:\n", sqrt_tensor)

exp_tensor = tf.exp(tensor_from_list)
print("Exponential tensor:\n", exp_tensor)

log_tensor = tf.math.log(tensor_from_list)
print("Logarithm tensor:\n", log_tensor)


Square root tensor:
 tf.Tensor(
[[1.        1.4142135]
 [1.7320508 2.       ]], shape=(2, 2), dtype=float32)
Exponential tensor:
 tf.Tensor(
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(2, 2), dtype=float32)
Logarithm tensor:
 tf.Tensor(
[[0.        0.6931472]
 [1.0986123 1.3862944]], shape=(2, 2), dtype=float32)


In [98]:
# 2. Keras

In [99]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [100]:
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(32,)))
model.add(Dense(10, activation='softmax'))

In [101]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [102]:
x_train = np.random.rand(1000, 32)
y_train = np.random.randint(0, 10, size=(1000, ))

In [103]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0935 - loss: 2.3429 
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1110 - loss: 2.3029
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1181 - loss: 2.2885
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1393 - loss: 2.2828
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1361 - loss: 2.2760
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1240 - loss: 2.2740
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1424 - loss: 2.2699
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1520 - loss: 2.2686
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1423 - loss: 2.2536
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1764 - loss: 2.2430


In [104]:
# Other operations in keras

In [105]:
import tensorflow as tf
from tensorflow.keras import backend as k
import numpy as np

In [106]:
tensor_from_list = k.constant([[1, 2], [3, 4]])
print(tensor_from_list)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [107]:
random_tensor = k.random_uniform(shape=(2, 3), minval=0, maxval=10)
print("Random tensor:\n", random_tensor)

zero_tensor = k.zeros(shape=(2, 3))
print("Zero tensor:\n", zero_tensor)

ones_tensor = k.ones(shape=(2, 3))
print("Ones tensor:\n", ones_tensor)

Random tensor:
 tf.Tensor(
[[8.098754  1.255902  9.310787 ]
 [4.9607205 5.432905  1.0422826]], shape=(2, 3), dtype=float32)
Zero tensor:
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
Ones tensor:
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [108]:
a = k.constant([[1, 2], [3, 4]])
b = k.constant([[5, 6], [7, 8]])
print("Addition:\n", k.eval(a + b))
print("Subtraction:\n", k.eval(a - b))
print("Multiplication:\n", k.eval(a * b))
print("Division:\n", k.eval(a / b))

Addition:
 [[ 6.  8.]
 [10. 12.]]
Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Multiplication:
 [[ 5. 12.]
 [21. 32.]]
Division:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]


In [109]:
tensor_to_reshape = k.constant([[1, 2, 3, 4], [5, 6, 7, 8]])
reshaped_tensor = k.reshape(tensor_to_reshape, shape=(4, 2))
print("Reshaped tensor:\n", k.eval(reshaped_tensor))
sliced_tensor = tensor_to_reshape[:, 1:3]
print("Sliced tensor:\n", k.eval(sliced_tensor))

Reshaped tensor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Sliced tensor:
 [[2. 3.]
 [6. 7.]]


In [110]:
tensor_a = k.constant([[1, 2], [3, 4]])
tensor_b = k.constant([[5, 6]])
concatenated_tensor = k.concatenate([tensor_a, tensor_b], axis=0)
print("Concatenated tensor:\n", k.eval(concatenated_tensor))

Concatenated tensor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [111]:
sqrt_tensor = k.sqrt(k.cast(tensor_from_list, dtype='float32'))
print("Square root tensor:\n", k.eval(sqrt_tensor))

exp_tensor = k.exp(k.cast(tensor_from_list, dtype='float32'))
print("Exponential tensor:\n", k.eval(exp_tensor))

log_tensor = k.log(k.cast(tensor_from_list, dtype='float32'))
print("Logarithm tensor:\n", k.eval(log_tensor))

Square root tensor:
 [[1.        1.4142135]
 [1.7320508 2.       ]]
Exponential tensor:
 [[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]]
Logarithm tensor:
 [[0.        0.6931472]
 [1.0986123 1.3862944]]


In [112]:
tensor_np = k.constant([[1.0, 2.0], [3.0, 4.0]])
np_array = k.eval(tensor_np)
print("Converted to NumPy array:\n", np_array)

np_array = np.array([[5.0, 6.0], [7.0, 8.0]])
tensor_from_np = k.constant(np_array)
print("Converted back to Tensor:\n", k.eval(tensor_from_np))

Converted to NumPy array:
 [[1. 2.]
 [3. 4.]]
Converted back to Tensor:
 [[5. 6.]
 [7. 8.]]


In [113]:
# 3. Theano

In [ ]:
import theano
import theano.tensor as T
import numpy as np

In [ ]:
x = T.dmatrix('x')
w = T.dmatrix('w')
b = T.dvector('b')

In [ ]:
y = T.dot(x, w) + b

In [ ]:
model = theano.function(inputs=[x, w, b], outputs=y)

In [ ]:
x_data = np.random.rand(100, 32)
w_data = np.random.rand(32, 10)
b_data = np.random.rand(10)

In [ ]:
output = model(x_data, w_data, b_data)
print(output)

In [ ]:
# other operations in theano

In [ ]:
import theano
import theano.tensor as T
import numpy as np

In [ ]:
a = T.matrix('a')
b = T.matrix('b')

In [ ]:
a_val = np.array([[1, 2], [3, 4]], dtype=theano.config.floatX)
b_val = np.array([[5, 6], [7, 8]], dtype=theano.config.floatX)

add_result = a + b
sub_result = a - b
mul_result = a * b
div_result = a / b

f_add = theano.function([a, b], add_result)
f_sub = theano.function([a, b], sub_result)
f_mul = theano.function([a, b], mul_result)
f_div = theano.function([a, b], div_result)

print("Addition:\n", f_add(a_val, b_val))
print("Subtraction:\n", f_sub(a_val, b_val))
print("Multiplication:\n", f_mul(a_val, b_val))
print("Division:\n", f_div(a_val, b_val))

In [ ]:
reshaped_tensor = a.reshape((4, 1))
f_reshape = theano.function([a], reshaped_tensor)
print("Reshaped tensor:\n", f_reshape(a_val))

In [ ]:
concat_result = T.concatenate([a, b], axis=0)
f_concat = theano.function([a, b], concat_result)
print("Concatenated tensor along axis 0:\n", f_concat(a_val, b_val))

In [ ]:
sqrt_tensor = T.sqrt(a)
exp_tensor = T.exp(a)
log_tensor = T.log(a)

# Compile functions
f_sqrt = theano.function([a], sqrt_tensor)
f_exp = theano.function([a], exp_tensor)
f_log = theano.function([a], log_tensor)

print("Square root tensor:\n", f_sqrt(a_val))
print("Exponential tensor:\n", f_exp(a_val))
print("Logarithm tensor:\n", f_log(a_val))

In [ ]:
np_array = np.array([[5.0, 6.0], [7.0, 8.0]], dtype=theano.config.floatX)
tensor_from_np = T.as_tensor_variable(np_array)
print("Tensor from NumPy array:\n", tensor_from_np.eval())

In [115]:
# 4. PyTorch

In [116]:
import torch
import torch.nn as nn
import torch.optim as optim

In [117]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(32, 64)
        self.fc2 = nn.Linear(64, 10)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

In [118]:
model = SimpleNN()

In [119]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [120]:
x_train = torch.rand(1000, 32)
y_train = torch.randint(0, 10, (1000,))

In [121]:
for epoch in range(10):
    model.train()
    optimizer.zero_grad()
    outputs = model(x_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    print(f'Epoch [{epoch+1}/10], Loss: {loss.item():.4f}')

Epoch [1/10], Loss: 2.3209
Epoch [2/10], Loss: 2.3172
Epoch [3/10], Loss: 2.3139
Epoch [4/10], Loss: 2.3109
Epoch [5/10], Loss: 2.3081
Epoch [6/10], Loss: 2.3055
Epoch [7/10], Loss: 2.3031
Epoch [8/10], Loss: 2.3010
Epoch [9/10], Loss: 2.2989
Epoch [10/10], Loss: 2.2970


In [122]:
# other operations in pytorch

In [123]:
import torch
import numpy as np

In [124]:
data = [[1, 2], [3, 4]]
tensor_from_list = torch.tensor(data)
print("Tensor from list:\n", tensor_from_list)

random_tensor = torch.rand((2, 3))
print("Random tensor:\n", random_tensor)

zero_tensor = torch.zeros((2, 3))
print("Zero tensor:\n", zero_tensor)

ones_tensor = torch.ones((2, 3))
print("Ones tensor:\n", ones_tensor)

Tensor from list:
 tensor([[1, 2],
        [3, 4]])
Random tensor:
 tensor([[0.5564, 0.4543, 0.5608],
        [0.3731, 0.8195, 0.5030]])
Zero tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [125]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Subtraction:
 tensor([[-4., -4.],
        [-4., -4.]])
Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Division:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [126]:
tensor_to_reshape = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
reshaped_tensor = tensor_to_reshape.view(4, 2)
print("Reshaped tensor:\n", reshaped_tensor)
sliced_tensor = tensor_to_reshape[:, 1:3]
print("Sliced tensor:\n", sliced_tensor)

Reshaped tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Sliced tensor:
 tensor([[2, 3],
        [6, 7]])


In [127]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6]])
concatenated_tensor = torch.cat([tensor_a, tensor_b], dim=0)
print("Concatenated tensor along rows:\n", concatenated_tensor)

Concatenated tensor along rows:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [128]:
sqrt_tensor = torch.sqrt(a)
print("Square root tensor:\n", sqrt_tensor)

exp_tensor = torch.exp(a)
print("Exponential tensor:\n", exp_tensor)

log_tensor = torch.log(a)
print("Logarithm tensor:\n", log_tensor)

Square root tensor:
 tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])
Exponential tensor:
 tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])
Logarithm tensor:
 tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])


In [129]:
tensor_np = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
np_array = tensor_np.numpy()
print("Converted to NumPy array:\n", np_array)

np_array = np.array([[5.0, 6.0], [7.0, 8.0]])
tensor_from_np = torch.from_numpy(np_array)
print("Converted back to Tensor:\n", tensor_from_np)

Converted to NumPy array:
 [[1. 2.]
 [3. 4.]]
Converted back to Tensor:
 tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)
